### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by christianpeel** [IBM/AutoMLPipeline.jl#3]
Your readme has links to "stable" and "dev" docs, but it appears neither link works.  I don't even see a `docs` subdirectory.

**Comment by ppalmes** [comment]
hi @christianpeel: i haven’t got the time yet to write the doc. i borrowed a lot of the idea from my previous package and extended it to cover generic ml datasets instead of just time-series. i think you’ve reviewed the doc of it: https://ibm.github.io/TSML.jl/latest/. 

ill try to write the doc in the coming days. best doc right now is to check the test directory for some sample usage. it is quiet straightforward. similar to unix pipe,
you can step by step add the elements in the pipe to see what they do in the README examples. the source files are also very small. I wrote the code in 3 days. of course my experience in previous package helped a lot. the current one is highly readable after the realization that the pipeline is the main driver in ML modeling.

**Comment by ppalmes** [comment]
Online doc is cooking. The dev branch of documentation is now available. It may take several days to finish the tutorial and docstring embedded in each function.

**Comment by ppalmes** [comment]
The documentation is almost done so I'm closing this. Just issue a PR for something that is not clear. The docstring is also available for some important functions and structures.

**Comment by ppalmes** [comment]
https://ibm.github.io/AutoMLPipeline.jl/dev/
